import assert from 'node:assert/strict';
import test from 'node:test';
import {
  assessGeneratedProjectPlan,
  assessGeneratedProjectQuality,
  GENERATED_PROJECT_QUALITY_LIMITS,
  LEGACY_GENERATED_PROJECT_QUALITY_LIMITS,
  renderGeneratedProjectSpec,
} from './generated-project-quality.js';

const bytes = (value) => new TextEncoder().encode(value);

const richPlan = {
  title: '耐久任务回执协调服务',
  overview: '实现带并发一致性控制、SQLite 持久化和重启恢复的 Go 服务，提供确定性公开测试。',
  business_flows: ['创建任务并冻结策略快照后进入排程，再按租约执行并记录结果。', '执行失败时进入隔离与人工接管，恢复确认后才能关闭任务。', '进程重启后重放已提交事件并恢复未完成租约，迟到命令只留下审计记录。'],
  components: ['领域状态机', 'SQLite 存储', '并发协调器', '恢复服务', 'HTTP 服务'],
  domain_rules: ['同一任务代次只能有一个终局状态。', '相同幂等键和规范化内容必须返回同一结果。', '修订号不匹配的命令不得改变状态。', '资源租约在同一事务中占用和释放。', '恢复流程不得重复执行已提交命令。', '失败隔离未解除时不得继续执行。', '迟到回调只能追加审计而不能推进状态。', '公开接口的错误码和字段必须稳定。'],
  data_model: ['任务聚合保存状态、代次、修订号和终局信息。', 'SQLite 事件表保存命令结果与审计顺序。', '资源租约表保存占用者、过期时间和唯一约束。', '恢复游标保存重启后待处理的事务边界。', '策略快照保存任务创建时使用的不可变规则。'],
  interfaces: ['POST /tasks 创建任务并返回冻结快照。', 'POST /tasks/{id}/schedule 按修订号申请窗口。', 'POST /tasks/{id}/complete 提交执行结果并保持幂等。', 'POST /tasks/{id}/takeover 进入人工接管终局。', 'GET /tasks/{id}/timeline 返回稳定审计时间线。'],
  failure_boundaries: ['数据库事务中断不得留下孤立租约。', '并发排程冲突必须返回可重试错误。', '旧代次回调不得覆盖新代次状态。', '恢复时损坏事件必须停止推进并报告位置。', '人工接管后自动执行只能被拒绝并写审计。'],
  acceptance: ['重复命令幂等', '并发冲突可判定', '重启后状态恢复', '损坏记录拒绝', '公开测试可复现', '事务失败回滚', '接口错误稳定'],
  test_scenarios: ['重复创建命令返回相同任务。', '两个排程器竞争同一窗口只有一个成功。', '执行进程在提交后立刻重启能够恢复结果。', '损坏事件导致恢复停止在确定位置。', '旧修订命令返回冲突且状态不变。', '人工接管与迟到回调并发只形成一个终局。', '租约过期后新任务可以重新占用资源。', 'HTTP 查询返回固定排序的审计时间线。'],
  component_traceability: ['领域状态机覆盖创建、执行、隔离和终局规则。', 'SQLite 存储覆盖事件、租约、快照和恢复游标。', '并发协调器覆盖排程竞争、幂等和修订冲突。', '恢复服务覆盖重启重放、损坏边界和租约回收。', 'HTTP 服务覆盖公开接口、错误语义和审计查询。'],
};

function projectEntries({ fileCount = 20, linesPerFile = 105, functionsPerFile = 3, frontend = false, generatedPadding = 0 } = {}) {
  const entries = [
    { path: 'go.mod', content: bytes('module example.com/task\n\ngo 1.23\n') },
    { path: 'run_benzhi_smoke.sh', content: bytes('#!/usr/bin/env bash\nset -euo pipefail\ngo run ./cmd/task --help\n') },
    { path: 'PROJECT_SPEC.md', content: bytes(renderGeneratedProjectSpec(richPlan)) },
    { path: 'cmd/task/main.go', content: bytes('package main\n\nimport (\n _ "example.com/task/internal/pkg0"\n _ "example.com/task/internal/pkg1"\n _ "example.com/task/internal/pkg2"\n _ "example.com/task/internal/pkg3"\n)\n\nfunc main() {}\n') },
  ];
  for (let index = 0; index < fileCount - 1; index += 1) {
    const packageIndex = index % 4;
    const functions = Array.from({ length: functionsPerFile }, (_, functionIndex) => `func Step${index}_${functionIndex}(v int) int { if v > ${functionIndex} { for j := 0; j < 1; j++ { v += j } }; return v }`).join('\n');
    const declarations = Array.from({ length: linesPerFile }, (_, line) => `var Value${index}_${line} = ${index * linesPerFile + line}`).join('\n');
    const persistence = index === 0 ? '\nvar Persist = os.WriteFile\n' : '';
    entries.push({
      path: `internal/pkg${packageIndex}/file${index}.go`,
      content: bytes(`package pkg${packageIndex}\n${index === 0 ? 'import "os"\n' : ''}${functions}\n${declarations}${persistence}`),
    });
  }
  for (let index = 0; index < 4; index += 1) {
    const tests = Array.from({ length: 3 }, (_, testIndex) => `func TestBehavior${index}_${testIndex}(t *testing.T) { t.Helper() }`).join('\n');
    entries.push({ path: `internal/pkg${index}/public_test.go`, content: bytes(`package pkg${index}\nimport "testing"\n${tests}\n`) });
  }
  if (generatedPadding) entries.push({
    path: 'internal/generated/padding.pb.go',
    content: bytes(`// Code generated by test. DO NOT EDIT.\npackage generated\n${Array.from({ length: generatedPadding }, (_, index) => `var Padding${index} = ${index}`).join('\n')}`),
  });
  if (frontend) entries.push(
    { path: 'web/package.json', content: bytes('{"scripts":{"build":"vite build"}}') },
    { path: 'web/package-lock.json', content: bytes('{}') },
    { path: 'web/src/App.tsx', content: bytes('export async function load() { return fetch("/api/health") }') },
  );
  return entries;
}

test('0-1 plan minimum quality requires persistence, concurrency and public tests', () => {
  assert.equal(assessGeneratedProjectPlan(richPlan).ok, true);
  const weakPlan = { title: '简单状态机', overview: '实现一个内存状态机', components: ['状态机'], acceptance: ['可运行'] };
  const result = assessGeneratedProjectPlan(weakPlan);
  assert.equal(result.ok, false);
  assert.match(result.issues.join(';'), /持久化/);
  assert.match(result.issues.join(';'), /恢复/);
  assert.match(result.issues.join(';'), /核心组件/);
});

test('standard generated project requires 20 production files and 2000 effective production lines', () => {
  const result = assessGeneratedProjectQuality(projectEntries(), richPlan);
  assert.equal(result.ok, true, result.issues.join('; '));
  assert.equal(result.productionGoFiles, 20);
  assert.ok(result.productionCodeLines >= 2000);
  assert.equal(result.projectTier, 'standard');
  assert.equal(result.bugQuota, 10);
  assert.equal(result.runtimeSmoke.ok, true);
});

test('large generated project requires 50 production files and 5000 effective production lines', () => {
  const result = assessGeneratedProjectQuality(projectEntries({ fileCount: 50 }), richPlan);
  assert.equal(result.ok, true, result.issues.join('; '));
  assert.equal(result.projectTier, 'large');
  assert.equal(result.bugQuota, 30);
});

test('generated code, tests and frontend do not inflate production Go eligibility', () => {
  const result = assessGeneratedProjectQuality(projectEntries({ fileCount: 19, generatedPadding: 3000 }), richPlan);
  assert.equal(result.ok, false);
  assert.equal(result.productionGoFiles, 19);
  assert.match(result.issues.join(';'), /生产 Go 文件过少/);
});

test('blank lines and block comments do not count as production code', () => {
  const entries = projectEntries({ linesPerFile: 10 });
  entries.push({ path: 'internal/pkg0/comment_only.go', content: bytes(`package pkg0\n/*\n${'padding text\n'.repeat(3000)}*/\n`) });
  const result = assessGeneratedProjectQuality(entries, richPlan);
  assert.equal(result.ok, false);
  assert.ok(result.productionCodeLines < 2000);
  assert.match(result.issues.join(';'), /生产 Go 有效代码量过少/);
});

test('frontend quota requires buildable source with a backend interaction', () => {
  const accepted = assessGeneratedProjectQuality(projectEntries({ frontend: true }), { ...richPlan, frontend_required: true });
  assert.equal(accepted.ok, true, accepted.issues.join('; '));
  assert.equal(accepted.frontend.backendIntegration, true);
  const nestedRootSource = projectEntries();
  nestedRootSource.push(
    { path: 'webembed/frontend/package.json', content: bytes('{"scripts":{"build":"node build.mjs"}}') },
    { path: 'webembed/frontend/package-lock.json', content: bytes('{}') },
    { path: 'webembed/frontend/app.js', content: bytes('export async function load() { return fetch("/api/health") }') },
  );
  const nestedAccepted = assessGeneratedProjectQuality(nestedRootSource, { ...richPlan, frontend_required: true });
  assert.equal(nestedAccepted.ok, true, nestedAccepted.issues.join('; '));
  assert.equal(nestedAccepted.frontend.frontendDir, 'webembed/frontend');
  const missing = projectEntries({ frontend: true }).filter((entry) => entry.path !== 'web/package-lock.json');
  assert.match(assessGeneratedProjectQuality(missing, { ...richPlan, frontend_required: true }).issues.join(';'), /真实页面/);
});

test('historical projects retain the legacy quality thresholds', () => {
  const legacy = projectEntries({ fileCount: 8, linesPerFile: 300, functionsPerFile: 6 }).filter((entry) => entry.path !== 'run_benzhi_smoke.sh');
  const result = assessGeneratedProjectQuality(legacy, richPlan, LEGACY_GENERATED_PROJECT_QUALITY_LIMITS);
  assert.equal(result.ok, true, result.issues.join('; '));
  assert.equal(GENERATED_PROJECT_QUALITY_LIMITS.requireRuntimeSmoke, true);
  assert.equal(LEGACY_GENERATED_PROJECT_QUALITY_LIMITS.requireRuntimeSmoke, false);
});

test('generated project quality rejects a thin domain-only project', () => {
  const result = assessGeneratedProjectQuality([
    { path: 'go.mod', content: bytes('module example.com/task\n\ngo 1.23\n') },
    { path: 'internal/domain/domain.go', content: bytes('package domain\nfunc Run() {}\n') },
    { path: 'internal/domain/domain_test.go', content: bytes('package domain\nfunc TestRun() {}\n') },
  ], richPlan);
  assert.equal(result.ok, false);
  assert.match(result.issues.join(';'), /生产 Go 文件过少/);
  assert.match(result.issues.join(';'), /生产 Go 有效代码量过少/);
  assert.match(result.issues.join(';'), /持久化/);
  assert.match(result.issues.join(';'), /业务逻辑过于简单/);
  assert.match(result.issues.join(';'), /run_benzhi_smoke\.sh/);
});

test('generated project quality rejects production packages disconnected from every executable', () => {
  const entries = projectEntries();
  entries.push({ path: 'internal/orphan/service.go', content: bytes('package orphan\n\nfunc PublicButDisconnected() int { return 1 }\n') });
  const result = assessGeneratedProjectQuality(entries, richPlan);
  assert.equal(result.ok, false);
  assert.deepEqual(result.runtimeReachability.unreachablePackages, ['internal/orphan']);
  assert.match(result.issues.join(';'), /未接入可执行入口/);
});

test('generated project quality rejects unreferenced internal declarations', () => {
  const entries = projectEntries().map((entry) => entry.path === 'internal/pkg0/file0.go'
    ? { ...entry, content: bytes(`${new TextDecoder().decode(entry.content)}\nfunc hiddenOnly() int { return 1 }\n`) }
    : entry);
  const result = assessGeneratedProjectQuality(entries, richPlan);
  assert.equal(result.ok, false);
  assert.ok(result.deadDeclarations.some((item) => item.endsWith(':hiddenOnly')));
  assert.match(result.issues.join(';'), /未被生产代码或测试引用/);
});

test('generated project quality rejects substantial copy-pasted function bodies', () => {
  const repeatedBody = `{
    total := 0
    for index := 0; index < 20; index++ {
      if index%2 == 0 { total += index } else { total -= index }
      if total > 50 { total = total / 2 }
      if total < -50 { total = total + 17 }
    }
    for total < 100 { total += 3; if total%7 == 0 { total += 2 } }
    if total == 101 { total = 99 }
    return total
  }`;
  const entries = projectEntries().map((entry) => {
    if (entry.path === 'internal/pkg0/file0.go') return { ...entry, content: bytes(`${new TextDecoder().decode(entry.content)}\nfunc DuplicateOne() int ${repeatedBody}\n`) };
    if (entry.path === 'internal/pkg1/file1.go') return { ...entry, content: bytes(`${new TextDecoder().decode(entry.content)}\nfunc DuplicateTwo() int ${repeatedBody}\n`) };
    return entry;
  });
  const result = assessGeneratedProjectQuality(entries, richPlan);
  assert.equal(result.ok, false);
  assert.equal(result.duplicateImplementations.length, 1);
  assert.match(result.issues.join(';'), /大段重复函数实现/);
});

test('generated project quality keeps the approved project document immutable', () => {
  const entries = projectEntries().map((entry) => entry.path === 'PROJECT_SPEC.md'
    ? { ...entry, content: bytes(`${new TextDecoder().decode(entry.content)}\n临时添加的未审批功能。\n`) }
    : entry);
  const result = assessGeneratedProjectQuality(entries, richPlan);
  assert.equal(result.projectSpec.matchesPlan, false);
  assert.match(result.issues.join(';'), /不得改写项目文档/);
});
